version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: bosco-backend-image
    container_name: bosco-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      # You can add MongoDB URI here if needed for the assignment to fully work
      # - MONGO_URI=mongodb+srv://...

  frontend:
    build:
      context: ./frontend
    image: bosco-frontend-image
    container_name: bosco-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
